markdown: redcarpet
paginate: 30
paginate_path: ":num"
pygments: true
permalink: /:title/

name: GetSharebar.com
title: "Sharebar - Share your content easily"
author: Monji Dolon
description: "Sharebar is a standalone JavaScript and WordPress plugin that makes it easy to share your content."
url: http://getsharebar.com

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Capfile', 'Guardfile']

authors:
  mdolon:
    display_name: "Monji Dolon"
    pic: "/assets/images/authors/mdolon.jpg"
    email: "mdolon@gmail.com"
    web: "http://www.mdolon.com/"
    twitter: "mdolon"
    github: "mdolon"
    bio: "Monji is a product designer and front-end developer.  In his free time, he likes to play guitar, climb tall mountains and go surfing.  You can find his portfolio at <a href='http://mdolon.com/'>mdolon.com</a>."